### ISSUE TITLE
yara-python fails to build on OS X 10.8.5

### ISSUE THREAD

**Issue by plusvic** [VirusTotal/yara#93]
_From [dko...@gmail.com](https://code.google.com/u/110901915239285628046/) on October 12, 2013 19:59:18_

What steps will reproduce the problem? 1. python setup.py build What is the expected output? What do you see instead? bash-3.2# python setup.py build
running build
running build_ext
building 'yara' extension
cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c yara-python.c -o build/temp.macosx-10.8-x86_64-2.7/yara-python.o
yara-python.c:258: error: expected specifier-qualifier-list before ‘,’ token
yara-python.c:321: error: expected declaration specifiers or ‘...’ before ‘YARA_CONTEXT’
yara-python.c: In function ‘process_externals’:
yara-python.c:338: warning: implicit declaration of function ‘yr_define_integer_variable’
yara-python.c:338: error: ‘context’ undeclared (first use in this function)
yara-python.c:338: error: (Each undeclared identifier is reported only once
yara-python.c:338: error: for each function it appears in.)
yara-python.c:342: warning: implicit declaration of function ‘yr_define_boolean_variable’
yara-python.c:346: warning: implicit declaration of function ‘yr_define_string_variable’
yara-python.c: At top level:
yara-python.c:358: error: expected declaration specifiers or ‘...’ before ‘YARA_CONTEXT’
yara-python.c: In function ‘Rules_new_from_file’:
yara-python.c:373: warning: implicit declaration of function ‘yr_push_file_name’
yara-python.c:373: error: ‘context’ undeclared (first use in this function)
yara-python.c:376: warning: implicit declaration of function ‘yr_compile_file’
yara-python.c:381: warning: implicit declaration of function ‘yr_get_error_message’
yara-python.c:391: error: ‘Rules’ has no member named ‘context’
yara-python.c: At top level: What version of the product are you using? On what operating system? 1.7 on OS X 10.8.5 with Python 2.7 Please provide any additional information below.

_Original issue: http://code.google.com/p/yara-project/issues/detail?id=93_
