### ISSUE TITLE
YARA fails to build with OpenSSL 4.0

### ISSUE THREAD

**Issue by loqs** [VirusTotal/yara#2232]
**Describe the bug**
YARA fails to build with OpenSSL 4.0 as the bundled authenticode-parser is incompatible.

**To Reproduce**
```
$ git clone https://github.com/VirusTotal/yara.git
$ cd yara
$ autoreconf -fiv
$ ./configure --with-crypto --enable-magic
$ make
....
libyara/modules/pe/authenticode-parser/certificate.c:68:47: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
   68 |         if (byte_array_init(&array, asn1String->data, asn1String->length) == -1)
      |                                               ^~
libyara/modules/pe/authenticode-parser/certificate.c:68:65: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
   68 |         if (byte_array_init(&array, asn1String->data, asn1String->length) == -1)
      |                                                                 ^~
libyara/modules/pe/authenticode-parser/certificate.c: In function 'certificate_new':
libyara/modules/pe/authenticode-parser/certificate.c:291:29: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  291 |     X509_NAME* issuerName = X509_get_issuer_name(x509);
      |                             ^~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/countersignature.c: In function 'pkcs9_countersig_new':
libyara/modules/pe/authenticode-parser/countersignature.c:144:32: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  144 |     ASN1_TYPE* messageDigest = PKCS7_get_signed_attribute(si, NID_pkcs9_messageDigest);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/countersignature.c:150:57: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  150 |     size_t digestLen = messageDigest->value.octet_string->length;
      |                                                         ^~
libyara/modules/pe/authenticode-parser/countersignature.c:163:66: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  163 |     const uint8_t* digestData = messageDigest->value.octet_string->data;
      |                                                                  ^~
libyara/modules/pe/authenticode-parser/certificate.c:300:30: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  300 |     X509_NAME* subjectName = X509_get_subject_name(x509);
      |                              ^~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/countersignature.c:190:38: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  190 |     uint8_t* encData = si->enc_digest->data;
      |                                      ^~
libyara/modules/pe/authenticode-parser/countersignature.c:191:35: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  191 |     size_t encLen = si->enc_digest->length;
      |                                   ^~
libyara/modules/pe/authenticode-parser/countersignature.c:223:50: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  223 |             isValid = !memcmp(digest_info->digest->data, calc_digest, mdLen);
      |                                                  ^~
libyara/modules/pe/authenticode-parser/countersignature.c:238:36: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  238 |     calculate_digest(md, enc_digest->data, enc_digest->length, calc_digest);
      |                                    ^~
libyara/modules/pe/authenticode-parser/countersignature.c:238:54: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  238 |     calculate_digest(md, enc_digest->data, enc_digest->length, calc_digest);
      |                                                      ^~
libyara/modules/pe/authenticode-parser/countersignature.c: In function 'ms_countersig_impl_get_ts_tst_info_cms_':
libyara/modules/pe/authenticode-parser/countersignature.c:272:37: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  272 |     const uint8_t* data = (*content)->data;
      |                                     ^~
libyara/modules/pe/authenticode-parser/countersignature.c:273:71: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  273 |     TS_TST_INFO* ts_tst_info = d2i_TS_TST_INFO(NULL, &data, (*content)->length);
      |                                                                       ^~
libyara/modules/pe/authenticode-parser/countersignature.c: In function 'ms_countersig_impl_verify_digest_pkcs7_':
libyara/modules/pe/authenticode-parser/countersignature.c:362:5: warning: 'TS_VERIFY_CTX_set_store' is deprecated: Since OpenSSL 3.4;Unclear semantics, replace with TS_VERIFY_CTX_set0_store(). [-Wdeprecated-declarations]
  362 |     TS_VERIFY_CTX_set_store(ctx, store);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from libyara/modules/pe/authenticode-parser/countersignature.c:32:
/usr/include/openssl/ts.h:434:13: note: declared here
  434 | X509_STORE *TS_VERIFY_CTX_set_store(TS_VERIFY_CTX *ctx, X509_STORE *s);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/countersignature.c:364:5: warning: 'TS_VERIFY_CTX_set_certs' is deprecated: Since OpenSSL 3.4;Unclear semantics, replace with TS_VERIFY_CTX_set0_certs(). [-Wdeprecated-declarations]
  364 |     TS_VERIFY_CTX_set_certs(ctx, impl->funcs->get_certs(impl));
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/ts.h:442:17: note: declared here
  442 | STACK_OF(X509) *TS_VERIFY_CTX_set_certs(TS_VERIFY_CTX *ctx, STACK_OF(X509) *certs);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/countersignature.c:368:5: warning: 'TS_VERIFY_CTX_set_imprint' is deprecated: Since OpenSSL 3.4;Unclear semantics, replace with TS_VERIFY_CTX_set0_imprint(). [-Wdeprecated-declarations]
  368 |     TS_VERIFY_CTX_set_imprint(ctx, digest, digest_size);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/ts.h:427:16: note: declared here
  427 | unsigned char *TS_VERIFY_CTX_set_imprint(TS_VERIFY_CTX *ctx,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/countersignature.c: In function 'ms_countersig_impl_verify_digest_cms_':
libyara/modules/pe/authenticode-parser/countersignature.c:403:26: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  403 |     if (ts_imprint_digest->length != (int)digest_size ||
      |                          ^~
libyara/modules/pe/authenticode-parser/countersignature.c:404:33: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  404 |         memcmp(ts_imprint_digest->data, digest, digest_size) != 0) {
      |                                 ^~
libyara/modules/pe/authenticode-parser/countersignature.c: In function 'ms_countersig_new':
libyara/modules/pe/authenticode-parser/countersignature.c:557:30: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  557 |     int digestLen = rawDigest->length;
      |                              ^~
libyara/modules/pe/authenticode-parser/countersignature.c:558:36: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  558 |     uint8_t* digestData = rawDigest->data;
      |                                    ^~
libyara/modules/pe/authenticode-parser/countersignature.c:574:36: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  574 |     calculate_digest(md, enc_digest->data, enc_digest->length, calc_digest);
      |                                    ^~
libyara/modules/pe/authenticode-parser/countersignature.c:574:54: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  574 |     calculate_digest(md, enc_digest->data, enc_digest->length, calc_digest);
      |                                                      ^~
make[1]: *** [Makefile:2070: libyara/modules/pe/authenticode-parser/la-certificate.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:2084: libyara/modules/pe/authenticode-parser/la-countersignature.lo] Error 1
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'get_content':
libyara/modules/pe/authenticode-parser/authenticode.c:81:47: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
   81 |     int len = content->d.other->value.sequence->length;
      |                                               ^~
libyara/modules/pe/authenticode-parser/authenticode.c:82:59: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
   82 |     const uint8_t* data = content->d.other->value.sequence->data;
      |                                                           ^~
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'parse_program_name':
libyara/modules/pe/authenticode-parser/authenticode.c:91:53: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
   91 |     const uint8_t* spcData = spcAttr->value.sequence->data;
      |                                                     ^~
libyara/modules/pe/authenticode-parser/authenticode.c:92:41: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
   92 |     int spcLen = spcAttr->value.sequence->length;
      |                                         ^~
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'parse_nested_authenticode':
libyara/modules/pe/authenticode-parser/authenticode.c:131:29: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  131 |         ASN1_TYPE* nested = X509_ATTRIBUTE_get0_type(attr, i);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/authenticode.c:134:41: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  134 |         int len = nested->value.sequence->length;
      |                                         ^~
libyara/modules/pe/authenticode-parser/authenticode.c:135:53: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  135 |         const uint8_t* data = nested->value.sequence->data;
      |                                                     ^~
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'parse_pkcs9_countersig':
libyara/modules/pe/authenticode-parser/authenticode.c:162:29: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  162 |         ASN1_TYPE* nested = X509_ATTRIBUTE_get0_type(attr, i);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/authenticode.c:165:41: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  165 |         int len = nested->value.sequence->length;
      |                                         ^~
libyara/modules/pe/authenticode-parser/authenticode.c:166:53: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  166 |         const uint8_t* data = nested->value.sequence->data;
      |                                                     ^~
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'parse_ms_countersig':
libyara/modules/pe/authenticode-parser/authenticode.c:193:29: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  193 |         ASN1_TYPE* nested = X509_ATTRIBUTE_get0_type(attr, i);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/authenticode.c:196:41: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  196 |         int len = nested->value.sequence->length;
      |                                         ^~
libyara/modules/pe/authenticode-parser/authenticode.c:197:53: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  197 |         const uint8_t* data = nested->value.sequence->data;
      |                                                     ^~
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'authenticode_verify':
libyara/modules/pe/authenticode-parser/authenticode.c:212:79: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  212 |     const uint8_t* contentData = p7->d.sign->contents->d.other->value.sequence->data;
      |                                                                               ^~
libyara/modules/pe/authenticode-parser/authenticode.c:213:68: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  213 |     long contentLen = p7->d.sign->contents->d.other->value.sequence->length;
      |                                                                    ^~
libyara/modules/pe/authenticode-parser/authenticode.c: In function 'authenticode_new':
libyara/modules/pe/authenticode-parser/authenticode.c:318:42: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  318 |     int digestLen = messageDigest->digest->length;
      |                                          ^~
libyara/modules/pe/authenticode-parser/authenticode.c:319:54: error: invalid use of incomplete typedef 'ASN1_OCTET_STRING' {aka 'struct asn1_string_st'}
  319 |     const uint8_t* digestData = messageDigest->digest->data;
      |                                                      ^~
libyara/modules/pe/authenticode-parser/authenticode.c:366:25: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  366 |     ASN1_TYPE* digest = PKCS7_get_signed_attribute(si, NID_pkcs9_messageDigest);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
libyara/modules/pe/authenticode-parser/authenticode.c:375:42: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  375 |     digestLen = digest->value.asn1_string->length;
      |                                          ^~
libyara/modules/pe/authenticode-parser/authenticode.c:376:43: error: invalid use of incomplete typedef 'ASN1_STRING' {aka 'struct asn1_string_st'}
  376 |     digestData = digest->value.asn1_string->data;
      |                                           ^~
libyara/modules/pe/authenticode-parser/authenticode.c:380:26: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  380 |     ASN1_TYPE* spcInfo = PKCS7_get_signed_attribute(si, OBJ_txt2nid(NID_spc_info));
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:2063: libyara/modules/pe/authenticode-parser/la-authenticode.lo] Error 1
````

**Expected behavior**
YARA should build with OpenSSL 4.0.

**Screenshots**
Not Applicable.

**Please complete the following information:**
 - Arch Linux Rolling
 - YARA HEAD https://github.com/VirusTotal/yara/commit/129cdc43fbe29f477540e89c9f71086acb08913c

**Additional context**
 - https://github.com/avast/authenticode-parser/issues/23
 - https://sources.debian.org/data/main/y/yara/4.5.7-1/debian/patches/Use-OpenSSL-accessor-functions-instead-of-direct-field-ac.patch
 - [yara-openssl-4.0-build-failure.log](https://github.com/user-attachments/files/30387224/yara-openssl-4.0-build-failure.log)

@anthraxx @pierres
