### ISSUE TITLE
Failure to build on trunk on ubuntu 12.04 x86_64

### ISSUE THREAD

**Issue by plusvic** [VirusTotal/yara#92]
_From [greg.mar...@threatstream.com](https://code.google.com/u/116639480565217344629/) on September 28, 2013 07:35:32_

make[3]: Entering directory `/opt/yara/libyara'
Making all in regex
make[4]: Entering directory`/opt/yara/libyara/regex'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory`/opt/yara/libyara/regex'
make[4]: Entering directory `/opt/yara/libyara'
make[4]: Leaving directory`/opt/yara/libyara'
make[3]: Leaving directory `/opt/yara/libyara'
make[2]: Leaving directory`/opt/yara/libyara'
make[2]: Entering directory `/opt/yara'
gcc -DHAVE_CONFIG_H -I.  -I./libyara -g -O3  -g -O3 -g -O2 -MT threading.o -MD -MP -MF .deps/threading.Tpo -c -o threading.o threading.c
threading.c: In function ‘semaphore_init’:
threading.c:75:39: error: ‘O_CREAT’ undeclared (first use in this function)
threading.c:75:39: note: each undeclared identifier is reported only once for each function it appears in
threading.c:75:48: error: ‘S_IRUSR’ undeclared (first use in this function)
make[2]: *** [threading.o] Error 1
make[2]: Leaving directory`/opt/yara'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/opt/yara'
make: **\* [all] Error 2

_Original issue: http://code.google.com/p/yara-project/issues/detail?id=92_
