### ISSUE TITLE
Can't compile with openssl < 1.0.0

### ISSUE THREAD

**Issue by Sibear-Jo** [VirusTotal/yara#1359]
Hello,

I tried compiling yara with OpenSSL 9.8.0c, as I didn't see any requirement for a minimum version and the configuration went fine, but the compilation failed because of some unknown types and functions.
```
libyara.c:86:24: error: unknown type name 'CRYPTO_THREADID'; did you mean 'CRYPTO_READ'?
   86 | static void _thread_id(CRYPTO_THREADID *id);
      |                        ^~~~~~~~~~~~~~~
      |                        CRYPTO_READ
libyara.c: In function 'yr_initialize':
libyara.c:154:3 warning: implicit declaration of function 'CRYPTO_THREADID_set_callback' [-Wimplicit-function-declaration]
  154 |   CRYPTO_THREADID_set_callback(_thread_id);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The issue is with the code added to make yara use openssl's crypto in a thread safe manner. That code is actually enabled by an preprocessor condition:
```
#if defined HAVE_LIBCRYPTO && OPENSSL_VERSION_NUMBER < 0x10100000L
```
But the functionnality was only made available from version 1.0.0 of openssl.
Adding `&& OPENSSL_VERSION_NUMBER >= 0x10000000L`  to that condition makes `libyara` compile, although making it unfit for multithreading.

Maybe an option could be added to willingly disable thread safety for monothread applications, so that compatibility with older versions of openssl could still be an option?
